name: vertx-infinispan (4.x)
on:
  schedule:
    - cron: '0 4 * * *'
jobs:
  CI:
    strategy:
      matrix:
        os: [ubuntu-latest]
        jdk: [8,11]
        profile: [ISPN-13, ISPN-14, ISPN-14-jakarta]
        exclude:
          - jdk: 8
            profile: ISPN-14
          - jdk: 8
            profile: ISPN-14-jakarta
          - jdk: 11
            profile: ISPN-13
    uses: ./.github/workflows/ci.yml
    with:
      branch: 4.x
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
    secrets: inherit
  Deploy:
    if: ${{ github.repository_owner == 'vert-x3' && (github.event_name == 'push' || github.event_name == 'schedule') }}
    needs: CI
    uses: ./.github/workflows/deploy.yml
    with:
      branch: 4.x
      jdk: 8
    secrets: inherit
