name: CI
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      jdk:
        default: 8
        type: string
      os:
        default: ubuntu-latest
        type: string
      profile:
        default: ISPN-13
        type: string
jobs:
  Test:
    name: Run tests
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ inputs.jdk }}
          distribution: temurin
      - name: Run tests
        run: mvn -s .github/maven-ci-settings.xml -B -DtestLogLevel=OFF test
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: heap-dump
          path: target/*.hprof
  Test-ISPN14:
    if: ${{ startsWith(github.event.inputs.profile, 'ISPN-14') }}
    name: Run tests
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ inputs.jdk }}
          distribution: temurin
      - name: Run tests
        run: mvn -P ${{ inputs.profile }} -s .github/maven-ci-settings.xml -B -DtestLogLevel=OFF test
